Welcome screen
MrZaiko/Polysmee pull request #172
Opened 2021-05-08 16:17 UTC by MRandl

2021-05-08 16:40 UTC, AttiaYoussef approved these changes

2021-05-08 16:44 UTC, MrZaiko requested changes

2021-05-08 16:44 UTC, MrZaiko commented on app/src/main/res/layout/activity_no_connection.xml
> +        android:layout_height="wrap_content"
Not a very good id

2021-05-08 16:44 UTC, MrZaiko commented on app/src/main/res/layout/activity_no_connection.xml
> +        android:layout_width="200dp"
same

2021-05-08 16:44 UTC, MrZaiko commented on app/src/main/res/layout/activity_no_connection.xml
> +        android:id="@+id/button2"
Same

2021-05-08 16:45 UTC, AttiaYoussef requested changes
Bad ids

2021-05-08 22:07 UTC, AttiaYoussef approved these changes

2021-05-09 13:47 UTC, MrZaiko approved these changes
Good work

2021-05-09 13:47 UTC, merged