UI invitations - Improved UI on invitations activity
MrZaiko/Polysmee pull request #178
Opened 2021-05-11 15:58 UTC by Morpheo1

2021-05-11 17:37 UTC, AttiaYoussef approved these changes
Looks good to me

2021-05-12 14:26 UTC, MrZaiko requested changes

2021-05-12 14:26 UTC, MrZaiko commented on app/src/main/res/layout/activity_invites_management.xml
> +                    android:layout_height="2dp"
Not a good id :)

2021-05-12 14:26 UTC, MrZaiko commented on app/src/main/res/layout/element_invitation_entry.xml
> +            android:layout_marginEnd="8dp"
Same here

2021-05-13 14:33 UTC, MrZaiko approved these changes

2021-05-13 14:53 UTC, merged