Appointment creation
MrZaiko/Polysmee pull request #23
Opened 2021-03-09 17:35 UTC by Morpheo1

Activity that allows the user to create an appointment easily. Resolves: #10 #7

2021-03-09 21:20 UTC, tombenamato requested changes
Documentation is really needed for the function but also for the overall class, I had a relatively hard time understanding what appointment activity was so imagine 4 weeks from now

2021-03-09 21:20 UTC, tombenamato commented on app/src/main/AndroidManifest.xml
>          </activity>
-The ACTION_MAIN action indicates this is the main entry point and does not expect any intent data.
  -The CATEGORY_LAUNCHER category indicates that this activity's icon should be placed in the system's app launcher. If the <activity> element does not specify an icon with icon, then the system uses the icon from the <application> element. see https://developer.android.com/guide/components/intents-filters
I do not think it is a ACTION_MAIN the main entry should be the activity where you see all you appointments and the public appointments. Moreover it is clearly not in the (or explain why) LAUNCHER category, do you want a launcher icon in the android system?

2021-03-09 22:33 UTC, MrZaiko approved these changes

2021-03-09 22:33 UTC, MrZaiko commented on app/src/main/java/io/github/polysmee/appointments/BasicAppointment.java
> +}
Javadoc

2021-03-09 22:33 UTC, MrZaiko commented on app/src/main/java/io/github/polysmee/appointments/AppointmentActivity.java
> +}
Javadoc

2021-03-09 22:33 UTC, MrZaiko commented on app/src/main/java/io/github/polysmee/appointments/AppointmentActivity.java
> +    TextView txtError, txtStartTime, txtEndTime;
Are they really needed ?

2021-03-09 22:41 UTC, Morpheo1 commented on app/src/main/AndroidManifest.xml
>          </activity>
I just made this to test the activity, then forgot to remove it, I just did along with documentation in the AppointmentActivity

2021-03-11 14:13 UTC, tombenamato requested changes

2021-03-11 14:13 UTC, tombenamato commented on app/src/main/java/io/github/polysmee/appointments/AppointmentActivity.java
> +    //A calendar is a wait to get time using year/month... and allows to transform it to epoch time
A calendar is a way** typo

2021-03-11 14:13 UTC, tombenamato commented on app/src/main/java/io/github/polysmee/appointments/AppointmentActivity.java
> +    Calendar date;
I think you should make the definition scope

2021-03-11 14:13 UTC, tombenamato commented on app/src/main/java/io/github/polysmee/appointments/AppointmentActivity.java
> +    Calendar date;
I think you should make the definition scope

2021-03-11 14:40 UTC, tombenamato requested changes

2021-03-11 14:40 UTC, tombenamato commented on app/src/main/res/values/strings.xml
> +    <string name="maximum_duration_of_an_appointment_is_4h">Maximum duration of an appointment is 4h</string>
Change key so that we know where it use, i.e in this activity

2021-03-11 14:53 UTC, tombenamato approved these changes

2021-03-11 15:02 UTC, merged