Calendar branch
MrZaiko/Polysmee pull request #25
Opened 2021-03-10 12:22 UTC by AttiaYoussef

I created the activity that shows the user's daily appointments, as well as the class that takes care of getting these appointments in order .

2021-03-10 20:16 UTC, MRandl approved these changes

2021-03-11 14:12 UTC, MrZaiko requested changes
XML ids

2021-03-11 15:02 UTC, MrZaiko requested changes
Sorry :( 
The format is : id = activityNameObjectName

2021-03-11 15:15 UTC, MrZaiko approved these changes

2021-03-11 15:52 UTC, merged