Messages edit and delete
MrZaiko/Polysmee pull request #66
Opened 2021-03-24 17:34 UTC by Fermeli

Refactored the database reader in RoomMessagesFragment, added edit and send messages functions and adapted the class so that it only uses Factories.

2021-03-24 20:02 UTC, tombenamato requested changes

2021-03-24 20:02 UTC, tombenamato commented on app/src/androidTest/java/io/github/polysmee/login/LoginCheckActivityTest.java
>  public class LoginCheckActivityTest {
you should merge main in this branch before merging back, so this will be corrected. Normally is not commented but in main it has been corrected

2021-03-24 20:02 UTC, tombenamato commented on app/src/androidTest/java/io/github/polysmee/roomActivityTests/TestMessages.java
> +>>>>>>> main
I think you forget this merge.

2021-03-25 17:47 UTC, MrZaiko approved these changes
Seems good

2021-03-25 18:24 UTC, tombenamato approved these changes

2021-03-25 18:46 UTC, merged